sudo: required
dist: trusty

language:
  - c++
  - objective-c

cache: ccache

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang

branches:
  only:
  - master
  - /^feature.*$/

before_install:
  - |
    if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-get update -q
      sudo apt-get install -y make autoconf man
      sudo apt-get install -y doxygen libxinerama-dev libxcursor-dev libasound2-dev
      sudo apt-get install -y libpango1.0-dev libcairo2-dev
    fi
    if [ $TRAVIS_OS_NAME == osx ]; then
      brew install ccache # need to install on OSX
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
      brew install doxygen
    fi
    
script:
  - |
   # Configure build
    autoconf
   if [ $TRAVIS_OS_NAME == linux ]; then
      ./configure --enable-pango --enable-cairo
   else
      ./configure
   fi

   # Build
   make
   
   # Generate doxygen documentation but build only once on first build
   if [ $TRAVIS_OS_NAME == linux ] && [ $CC == "gcc" ] ; then
       doxygen --version
       cd documentation
       make html
       cd -
    fi

notifications:
  email:
    recipients:
      - fabien@onepost.net
      