sudo: required
dist: trusty

language:
  - c++
  - objective-c

cache: ccache

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang

branches:
  only:
  - master
  - /^feature.*$/

before_install:
  - |
    if [ $TRAVIS_OS_NAME == linux ]; then
      sudo apt-get update -q
      sudo apt-get install -y doxygen libxinerama-dev libxcursor-dev libasound2-dev
    fi
    if [ $TRAVIS_OS_NAME == osx ]; then
      brew install ccache # need to install on OSX
      export PATH="/usr/local/opt/ccache/libexec:$PATH"
      brew install doxygen
    fi

script:
  - |
    autoconf
    ./configure
    make

notifications:
  email:
    recipients:
      - fabien@onepost.net
      