sudo: required
dist: trusty

language: c

os:
  - linux

compiler:
  - gcc
  - clang

branches:
  only:
  - /feature/travis-integration
#  - master

install:
  - sudo apt-get install autoconf

script:
  - |
    autoconf
    ./configure
    make
