sudo: required
dist: trusty

language:
  - c++
  - objective-c

cache: ccache

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang

branches:
  only:
  - master
  - /^feature.*$/

stages:
  - build
  - name: document
      if: (branch = master) AND (os = linux)
      
  # TODO: - test
  # TODO: - deploy

build-unix-configure:
  stage: build
  
  before_script:
    - if [ $TRAVIS_OS_NAME == linux ]; then
        sudo apt-get update -q
        sudo apt-get install -y make autoconf man
        sudo apt-get install -y libxinerama-dev libxcursor-dev libasound2-dev
        sudo apt-get install -y libpango1.0-dev libcairo2-dev
      elif [ $TRAVIS_OS_NAME == osx ]; then
        brew install ccache # need to install on OSX
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
      fi

  script:
    - autoconf
    - if [ $TRAVIS_OS_NAME == linux ]; then
        ./configure --enable-pango --enable-cairo
      else
        ./configure
      fi
    - make

document-with-doxygen:
  stage: document

  before_script:
    - if [ $TRAVIS_OS_NAME == osx ]; then
        brew install doxygen
      elif [ $TRAVIS_OS_NAME == linux ]; then
        sudo apt-get install -y doxygen
      fi

  script:
    - doxygen --version
    - cd documentation
    - make html
    - cd -

notifications:
  email:
    recipients:
      - fabien@onepost.net
